        Image(systemName: "rainbow")
            .resizable()
            .frame(width: 200, height: 120)
            .symbolRenderingMode(.multicolor)
            .symbolEffect(.variableColor.iterative.reversing.hideInactiveLayers)
